default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: rails5-boilerplate_development

test:
  <<: *default
  database: rails5-boilerplate_test

production:
  <<: *default
  database: rails5-boilerplate_production
  username: rails5-boilerplate
  password: <%= ENV['DATABASE_PASSWORD'] %>
